#!/bin/sh
#
# SpinForge OpenResty entrypoint
#
# Generates /etc/openresty/conf.d/real_ip.conf from environment variables
# before starting nginx. Keeps IP-level config out of the baked-in
# nginx.conf so operators can change the trusted HAProxy IP(s) without
# rebuilding the image — just tweak the env in docker-compose.yml and
# `docker compose up -d openresty`.
#
# Env vars:
#   HAPROXY_TRUSTED_IP  space-separated list of IPs or CIDRs that are
#                       allowed to send PROXY protocol v2 headers. Each
#                       entry becomes one `set_real_ip_from` directive.
#                       Default: 192.168.88.0/24 (the Proxmox LAN).
#
# Example:
#   HAPROXY_TRUSTED_IP="192.168.88.154 192.168.88.155"
#   → /etc/openresty/conf.d/real_ip.conf:
#       set_real_ip_from 192.168.88.154;
#       set_real_ip_from 192.168.88.155;
#       real_ip_header proxy_protocol;
#       real_ip_recursive on;

set -eu

CONF_DIR=/etc/openresty/conf.d
CONF_FILE="$CONF_DIR/real_ip.conf"
DEFAULT_TRUSTED="192.168.88.0/24"

mkdir -p "$CONF_DIR"

TRUSTED="${HAPROXY_TRUSTED_IP:-$DEFAULT_TRUSTED}"

{
  echo "# Auto-generated by docker-entrypoint.sh — DO NOT EDIT."
  echo "# Change HAPROXY_TRUSTED_IP in docker-compose.yml and restart the container."
  echo "# Each IP/CIDR listed here is allowed to send PROXY protocol v2 headers."
  for ip in $TRUSTED; do
    printf 'set_real_ip_from %s;\n' "$ip"
  done
  echo "real_ip_header proxy_protocol;"
  echo "real_ip_recursive on;"
} > "$CONF_FILE"

echo "[docker-entrypoint] wrote $CONF_FILE with trust list: $TRUSTED"

# Default SSL cert bootstrap. The image's Dockerfile generates a
# self-signed default cert at build time, but docker-compose mounts
# ${SPINFORGE_DATA_ROOT}/certs onto /etc/letsencrypt, which SHADOWS
# whatever the image shipped. On a fresh node with an empty data
# volume this means openresty can't load its default_server cert
# and crashloops. Regenerate if missing.
DEFAULT_CERT_DIR=/etc/letsencrypt/live/default
if [ ! -f "$DEFAULT_CERT_DIR/fullchain.pem" ] || [ ! -f "$DEFAULT_CERT_DIR/privkey.pem" ]; then
  echo "[docker-entrypoint] default SSL cert missing, generating self-signed"
  mkdir -p "$DEFAULT_CERT_DIR"
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout "$DEFAULT_CERT_DIR/privkey.pem" \
    -out   "$DEFAULT_CERT_DIR/fullchain.pem" \
    -subj "/C=US/ST=State/L=City/O=SpinForge/CN=localhost" 2>/dev/null
  echo "[docker-entrypoint] generated default cert at $DEFAULT_CERT_DIR"
fi

# Hand off to the original CMD (or whatever the operator passed).
exec "$@"
