#!/bin/sh
#
# SpinForge OpenResty entrypoint
#
# Generates /etc/openresty/conf.d/real_ip.conf from environment variables
# before starting nginx. Keeps IP-level config out of the baked-in
# nginx.conf so operators can change the trusted HAProxy IP(s) without
# rebuilding the image — just tweak the env in docker-compose.yml and
# `docker compose up -d openresty`.
#
# Env vars:
#   HAPROXY_TRUSTED_IP  space-separated list of IPs or CIDRs that are
#                       allowed to send PROXY protocol v2 headers. Each
#                       entry becomes one `set_real_ip_from` directive.
#                       Default: 192.168.88.0/24 (the Proxmox LAN).
#
# Example:
#   HAPROXY_TRUSTED_IP="192.168.88.154 192.168.88.155"
#   → /etc/openresty/conf.d/real_ip.conf:
#       set_real_ip_from 192.168.88.154;
#       set_real_ip_from 192.168.88.155;
#       real_ip_header proxy_protocol;
#       real_ip_recursive on;

set -eu

CONF_DIR=/etc/openresty/conf.d
CONF_FILE="$CONF_DIR/real_ip.conf"
DEFAULT_TRUSTED="192.168.88.0/24"

mkdir -p "$CONF_DIR"

TRUSTED="${HAPROXY_TRUSTED_IP:-$DEFAULT_TRUSTED}"

{
  echo "# Auto-generated by docker-entrypoint.sh — DO NOT EDIT."
  echo "# Change HAPROXY_TRUSTED_IP in docker-compose.yml and restart the container."
  echo "# Each IP/CIDR listed here is allowed to send PROXY protocol v2 headers."
  for ip in $TRUSTED; do
    printf 'set_real_ip_from %s;\n' "$ip"
  done
  echo "real_ip_header proxy_protocol;"
  echo "real_ip_recursive on;"
} > "$CONF_FILE"

echo "[docker-entrypoint] wrote $CONF_FILE with trust list: $TRUSTED"

# Hand off to the original CMD (or whatever the operator passed).
exec "$@"
