global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # SpinForge API metrics
  - job_name: 'spinforge-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis/KeyDB metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx/OpenResty metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Docker containers metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']