# Prometheus configuration for SpinForge

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'spinforge-monitor'

scrape_configs:
  # SpinHub metrics
  - job_name: 'spinhub'
    static_configs:
      - targets: ['spinhub:8080']
    metrics_path: '/_metrics'
    scrape_interval: 30s

  # KeyDB exporter (if using redis_exporter)
  - job_name: 'keydb'
    static_configs:
      - targets: ['keydb-exporter:9121']
    scrape_interval: 30s

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules (optional)
rule_files:
  # - 'alerts/*.yml'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'