version: '3.8'

services:
  vibe-flutter:
    # Use the published image from Docker Hub
    image: jaclight/platform:vibe-studio-flutter-latest
    # Optional: Build locally if needed
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: vibe-flutter-${APP_ENGINE_ORG_ID}-${APP_ENGINE_DEV_ENVIRONMENT:-flutter}
    ports:
      - "${DEV_PORT:-3000}:3000"
      - "${PREVIEW_PORT:-8888}:8888"
    volumes:
      # Dynamic volumes based on ORG_ID and DEV_ENVIRONMENT
      # VIBE_DATA_PATH can be set to any absolute path (default: ~/vibe-studio-data)
      - ${VIBE_DATA_PATH:-~/vibe-studio-data}/${APP_ENGINE_ORG_ID}/${APP_ENGINE_DEV_ENVIRONMENT:-flutter}/workspace:/workspace
      - ${VIBE_DATA_PATH:-~/vibe-studio-data}/${APP_ENGINE_ORG_ID}/${APP_ENGINE_DEV_ENVIRONMENT:-flutter}/deploy:/deploy
    environment:
      - FLUTTER_HOME=/opt/flutter
      - NODE_ENV=${NODE_ENV:-development}
      - ORG_ID=${APP_ENGINE_ORG_ID}
      - API_KEY=${APP_ENGINE_API_KEY}
      - ENV_NAME=${APP_ENGINE_DEV_ENVIRONMENT}
      - APPENGINE_ENDPOINT=${APP_ENGINE_BASE_URL:-https://appengine.appmint.io}
      - APP_ENGINE_BASE_URL=${APP_ENGINE_BASE_URL:-https://appengine.appmint.io}
      - APP_ENGINE_DEV_ENVIRONMENT=${APP_ENGINE_DEV_ENVIRONMENT}
      - APP_ENGINE_ORG_ID=${APP_ENGINE_ORG_ID}
      - APP_ENGINE_API_KEY=${APP_ENGINE_API_KEY}
      - APP_PREVIEW_URL=${APP_PREVIEW_URL:-https://preview-${APP_ENGINE_DEV_ENVIRONMENT}-${APP_ENGINE_ORG_ID}.appmint.app}
    restart: unless-stopped
    networks:
      - vibe-network

networks:
  vibe-network:
    driver: bridge